language: go

# Faster container-based builds
sudo: false

go:
  - "1.10.x"

jobs:
  include:
    - stage: "test"
      before_install:
        - "go get -u github.com/golang/dep/cmd/dep"
      install:
        - "dep ensure"
      script:
        - "go test -v --race --coverprofile=coverage.txt --covermode=atomic ./..."
      after_success:
        - "bash <(curl -s https://codecov.io/bash)"

#    - stage: "lint"
#      before_script:
#        - "go get -u gopkg.in/alecthomas/gometalinter.v2"
#        - "gometalinter.v2 --install"
#      script: "gometalinter.v2 --vendor ./..."
