language: go

go:
  - "1.x"

install:
  - "go get -u -v github.com/alecthomas/gometalinter"
  - "gometalinter --install"

jobs:
  include:
    - stage: "lint"
      script: "gometalinter --vendor ./..."
    - stage: "test"
      script: "go test -v --race ./..."
