language: go

go:
  - "1.x"

jobs:
  include:
    - stage: "lint"
      before_script:
        - "go get -u -v github.com/alecthomas/gometalinter"
        - "gometalinter --install"
      script: "gometalinter --vendor ./..."
    - stage: "test"
      script: "go test -v --race ./..."
