language: go

# Faster container-based builds
sudo: false

go:
  - "1.11.x"

env:
  global:
    - GORACE="halt_on_error=1"
# «For parallel processes running at the same time, try to reduce the number. More than two to four processes should be fine, beyond that, resources are likely to be exhausted.»
# https://docs.travis-ci.com/user/common-build-problems/#my-build-script-is-killed-without-any-error
    - GOMAXPROCS=2
    - CGO_ENABLED=0

before_install:
  - "go get -u github.com/golang/dep/cmd/dep"
install:
  - "dep ensure"
script:
  - "CGO_ENABLED=1 go test --race --coverprofile=coverage.txt --covermode=atomic ./..."
  - "go build -o insolard cmd/insolard/*"
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
