language: go

# Faster container-based builds
sudo: false

go:
  - "1.10.x"

jobs:
  include:
    - stage: "test"
      script: "go test -v --race ./..."
#    - stage: "lint"
#      before_script:
#        - "go get -u gopkg.in/alecthomas/gometalinter.v2"
#        - "gometalinter.v2 --install"
#      script: "gometalinter.v2 --vendor ./..."
