version: '3'
services:
  bootstrap:
    build: .
    restart: always
    ports:
    - "17000:17001"
  node:
    build: .
    ports:
    - "17000:17000"
    environment:
      INSOLAR_HOST_BOOTSTRAPHOSTS: bootstrap:17001
