apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-rest
  labels:
    app: elasticsearch-rest
spec:
  type: NodePort
  ports:
  - port: 9200
    nodePort: 30200
    name: elasticsearch-rest
  selector:
    app: elasticsearch

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    name: elasticsearch
    protocol: TCP
  - port: 9300
    name: elasticsearch-node
    protocol: TCP
  clusterIP: None
  selector:
    app: elasticsearch

---

apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    nodePort: 30601
    name: kibana
  selector:
    app: kibana

---

apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  containers:
    - name: elasticsearch
      image: "docker.elastic.co/elasticsearch/elasticsearch:6.5.4"
      tty: true
      stdin: true
      env:
        - name: ES_JAVA_OPTS
          value: "-Xmx256m -Xms256m"
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"

---

apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  containers:
    - name: kibana
      image: "docker.elastic.co/kibana/kibana:6.5.4"
      tty: true
      stdin: true
