apiVersion: v1
kind: Service
metadata:
  name: elk
  labels:
    app: elk
spec:
  type: NodePort
  ports:
  - port: 9200
    nodePort: 30200
    name: elasticsearch
  - port: 5601
    nodePort: 30601
    name: kibana
  selector:
    app: elk

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-local
  labels:
    app: elasticsearch-local
spec:
  ports:
  - port: 9200
    name: elasticsearch-local
    protocol: TCP
  clusterIP: None
  selector:
    app: elasticsearch-local

---

apiVersion: v1
kind: Pod
metadata:
  name: elk
  labels:
    app: elk
spec:
  hostname: "elasticsearch"
  containers:
    - name: elasticsearch
      image: "docker.elastic.co/elasticsearch/elasticsearch:6.5.4"
      imagePullPolicy: IfNotPresent
      tty: true
      stdin: true
      env:
        - name: ES_JAVA_OPTS
          value: "-Xmx256m -Xms256m"
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"
    - name: kibana
      image: "docker.elastic.co/kibana/kibana:6.5.4"
      imagePullPolicy: IfNotPresent
      tty: true
      stdin: true
