apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  type: NodePort
  ports:
  - port: 16686
    nodePort: 30686
    name: jaeger
  selector:
    app: jaeger

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  labels:
    app: jaeger-agent
spec:
  ports:
  - port: 6831
    protocol: UDP
    name: agent-compact
  selector:
    app: jaeger

---


apiVersion: v1
kind: Pod
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  containers:
    - name: jaeger
      image: "jaegertracing/all-in-one:1.8"
      imagePullPolicy: IfNotPresent
      tty: true
      stdin: true
#      env:
#        - name: SPAN_STORAGE_TYPE
#          value: "elasticsearch"
#        - name: ES_SERVER_URLS
#          value: "http://elk:9200"
#        - name: ES_TAGS_AS_FIELDS
#          value: "true"