apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  type: NodePort
  ports:
  - port: 16686
    nodePort: 30686
    name: jaeger
  selector:
    app: jaeger

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-udp
  labels:
    app: jaeger-udp
spec:
  ports:
  - port: 6831
    protocol: UDP
    name: jaeger-6831
  - port: 6832
    protocol: UDP
    name: jaeger-6832
  - port: 5775
    protocol: UDP
    name: jaeger-5775
  - port: 5778
    protocol: TCP
    name: jaeger-5778
  - port: 16686
    protocol: TCP
    name: jaeger-16686
  clusterIP: None
  selector:
    app: jaeger

---


apiVersion: v1
kind: Pod
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  containers:
    - name: jaeger
      image: "jaegertracing/all-in-one:1.8"
      imagePullPolicy: IfNotPresent
      tty: true
      stdin: true
#      env:
#        - name: SPAN_STORAGE_TYPE
#          value: "elasticsearch"
#        - name: ES_SERVER_URLS
#          value: "http://elk:9200"
#        - name: ES_TAGS_AS_FIELDS
#          value: "true"
