---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 2s

    scrape_configs:
      -
        job_name: 'heavy_material'
        static_configs:
        - targets:
          - "seed-0.bootstrap:8080"
      -
        job_name: 'light_material'
        static_configs:
        - targets:
          - "seed-2.bootstrap:8080"
          - "seed-4.bootstrap:8080"
      -
        job_name: 'virtual'
        static_configs:
        - targets:
          - "seed-1.bootstrap:8080"
          - "seed-3.bootstrap:8080"
---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    nodePort: 30090
    name: prometheus
  selector:
    app: prometheus

---

apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    app: prometheus

spec:
  containers:
    - name: prometheus
      image: "prom/prometheus:v2.6.0"
      tty: true
      stdin: true
      command:
        - /bin/prometheus
        - --config.file=/etc/prometheus/prometheus.yml
      volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
  volumes:
    - name: prometheus-config
      configMap:
        name: prometheus-config
