apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: pulsar
  namespace: dev
  labels:
    app: pulsar

spec:
  serviceName: pulsar
  replicas: 1
  template:
    metadata:
      labels:
        app: pulsar
    spec:
      terminationGracePeriodSeconds: 0
      initContainers:
        - name: init-register
          imagePullPolicy: Never
          image: "base"
          tty: true
          stdin: true
          command: 
            - /bin/sh
            - -c
            - |
              /go/bin/insolar -c default_config > /opt/insolar/config/config.yaml;
              /go/bin/insolar -c gen_keys > /opt/insolar/config/keys.json;
          env:
            - name: HOME
              value: /opt/insolar
            - name: INSOLAR_KEYSPATH
              value: "/opt/insolar/config/keys.json"
            - name: INSOLAR_GENESIS_ROOTKEYS
              value: "/opt/insolar/config/rootkeys.json"
            - name: INSOLAR_PULSAR_STORAGE_DATADIRECTORY
              value: "/opt/insolar/pulsar"
            - name: INSOLAR_LEDGER_STORAGE_DATADIRECTORY
              value: "/opt/insolar/data"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: INSOLAR_HOST_TRANSPORT_ADDRESS
              value: "$(POD_IP):7900"
          volumeMounts:
            - name: config
              mountPath: /opt/insolar/config
            - name: data
              mountPath: /opt/insolar/data
            - name: pulsar
              mountPath: /opt/insolar/pulsar
            - name: code
              mountPath: /tmp/code
            - name: root-keys
              mountPath: /opt/insolar/config/rootkeys.json
              subPath: rootkeys.json
      containers:
        - name: pulsar
          imagePullPolicy: Never
          image: "base"
          workingDir: "/opt/insolar"
          tty: true
          stdin: true
          command: 
            - /go/bin/pulsard
            - -c
            - /opt/insolar/config/config.yaml
          env:
            - name: HOME
              value: /opt/insolar
            - name: INSOLAR_PULSAR_BOOTSTRAPNODES
              value: "seed-0.bootstrap:7900"
            - name: INSOLAR_LOG_LEVEL
              value: "debug"
            - name: INSOLAR_KEYSPATH
              value: "/opt/insolar/config/keys.json"
            - name: INSOLAR_PULSAR_STORAGE_DATADIRECTORY
              value: "/opt/insolar/pulsar"
            - name: INSOLAR_LEDGER_STORAGE_DATADIRECTORY
              value: "/opt/insolar/data"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: INSOLAR_HOST_TRANSPORT_ADDRESS
              value: "$(POD_IP):7900"
            - name: INSOLAR_PULSAR_BOOTSTRAPLISTENER_ADDRESS
              value: "$(POD_IP):18091"
          resources:
            requests:
              cpu: 300m
              memory: 200M
          volumeMounts:
            - name: config
              mountPath: /opt/insolar/config
            - name: data
              mountPath: /opt/insolar/data
            - name: pulsar
              mountPath: /opt/insolar/pulsar
            - name: code
              mountPath: /tmp/code
            - name: root-keys
              mountPath: /opt/insolar/config/rootkeys.json
              subPath: rootkeys.json
      volumes:
      - name: config
        emptyDir: {}
      - name: data
        emptyDir: {}
      - name: pulsar
        emptyDir: {}
      - name: code
        emptyDir: {}
      - name: root-keys
        configMap:
          name: root-keys
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
