groups:
- name: master
  jobs:
    - insolard

resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.11"

resources:
- name: master
  type: git
  source:
    uri: https://github.com/insolar/insolar.git
    branch: release/v0.7.0-alpha
    #branch: INS-991-real-pulsar-update-conf

- name: insolard
  type: docker-image
  source:
    repository: registry.insolar.io/insolard
    username: ((meta.registry.username))
    password: ((meta.registry.password))

- name: adm
  type: git
  source:
    uri: git@github.com:insolar/adm.git
    branch: master
    private_key: ((meta.github.adm_key))

- name: k8s
  type: kubernetes
  source:
    server: https://kube.insolar.io:6443
    token: ((meta.kubernetes.block-explorer-token))
    certificate_authority: ((meta.kubernetes.ca))

jobs:
- name: insolard
  public: true
  plan:
  - get: master
    trigger: true
  - get: adm
    trigger: false
  - put: insolard
    params:
      build: master
      dockerfile: master/docker/Dockerfile.insolard
      tag_file: master/.git/short_ref
      tag_as_latest: true
  - put: k8s
    params:
      namespace: block-explorer
      wait_until_ready: 0
      kubectl: delete -f adm/manifests/block-explorer/bootstrap-ss.yaml
  - put: k8s
    params:
      namespace: block-explorer
      wait_until_ready: 0
      kubectl: delete -f adm/manifests/block-explorer/pulsar.yaml
  - task: set-tag
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      inputs:
        - name: master
        - name: adm
      outputs:
        - name: deploy
      run:
        path: sh
        args:
          - -exc
          - |
            cp master/.git/short_ref deploy/tag
            cp adm/manifests/block-explorer/bootstrap-ss.yaml deploy/bootstrap.yaml
            cp adm/manifests/block-explorer/pulsar.yaml deploy/pulsar.yaml
            ls -alh
            sed -i "s/registry.insolar.io\/insolard/registry.insolar.io\/insolard:$(cat deploy/tag)/g" deploy/bootstrap.yaml
            sed -i "s/registry.insolar.io\/insolard/registry.insolar.io\/insolard:$(cat deploy/tag)/g" deploy/pulsar.yaml
            cat deploy/bootstrap.yaml
  - put: k8s
    params:
      namespace: block-explorer
      wait_until_ready_selector: app=bootstrap
      wait_until_ready: 300
      kubectl: apply -f deploy/bootstrap.yaml
  - put: k8s
    params:
      namespace: block-explorer
      wait_until_ready_selector: app=pulsar
      wait_until_ready: 300
      kubectl: apply -f deploy/pulsar.yaml



