
resource_types:
- name: smuggler
  type: docker-image
  source:
    repository: redfactorlabs/concourse-smuggler-resource
    tag: alpine
- name: concourse-pipeline
  type: docker-image
  source:
    repository: chemist/concourse-pipeline-resource

resources:
- name: branches
  type: smuggler
  source:
    smuggler_debug: true
    target_file: branches.json
    commands:
      check: |
        curl https://api.github.com/repos/insolar/insolar/branches | jq -c '{ "branches": [.[] | .name]} ' | md5sum > ${SMUGGLER_OUTPUT_DIR}/versions
      in: |
        curl https://api.github.com/repos/insolar/insolar/branches | jq -c '{ "branches": [.[] | .name]} ' > ${SMUGGLER_DESTINATION_DIR}/${SMUGGLER_target_file}
        echo "date=$(date)" > ${SMUGGLER_OUTPUT_DIR}/metadata
        curl https://api.github.com/repos/insolar/insolar/branches | jq -c '{ "branches": [.[] | .name]} ' >> ${SMUGGLER_OUTPUT_DIR}/metadata

- name: deploy
  type: concourse-pipeline
  source:
    teams:
    - name: insolar
      username: ((username))
      password: ((password))

- name: insolar
  type: git
  source:
    uri: https://github.com/insolar/insolar.git
    branch: devops
    paths:
      - 'ci'

jobs:
- name: magic
  plan:
  - get: branches
    trigger: true
  - get: insolar
    trigger: false
  - task: generate_pipelines
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: chemist/alpine-jinja-cli
      inputs:
      - name: branches
      - name: insolar
      outputs:
      - name: pipelines
      run:
        path: sh
        args:
        - -ec
        - |
          echo Generate pipelines 
          echo "Input: $(cat branches/branches.json)"
          jinja2 insolar/ci/templates/insolar.yml.j2 branches/branches.json > pipelines/branches.yml
          echo "Output: "
          cat pipelines/branches.yml
  - put: deploy
    params:
      pipelines:
        - name: branches
          team: insolar
          config_file: pipelines/branches.yml


