resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource

resources:
- name: insolar
  type: git
  source:
    uri: https://github.com/insolar/insolar.git
    branch: devops
- name: multibranch
  type: git-multibranch
  source:
    uri: https://github.com/insolar/insolar.git
    branch: 'devops'
    branches: '.*'


jobs:
- name: unit-all
  public: true
  plan:
  - get: insolar
    trigger: false
  - task: unit
    file: insolar/ci/test.yml
- name: unit-network
  public: false
  plan:
  - get: multibranch
    trigger: true
  - task: unit-net
    file: multibranch/ci/test-net.yml

