groups:
- name: explorer
  jobs:
    - build-explorer

resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.11"

resources:
- name: adm
  type: git
  source:
    uri: git@github.com:insolar/adm.git
    branch: master
    private_key: ((meta.github.adm_key))

- name: git-explorer
  type: git
  source:
    #uri: https://git.websecret.by/developers/insolar
    uri: git@github.com:insolar/block-explorer-frontend.git
    branch: master
    private_key: ((meta.github.block-explorer-frontend))
    #username: ((meta.gitlab.websecret.username))
    #password: ((meta.gitlab.websecret.password))
    #
- name: registry-explorer
  type: docker-image
  source:
    repository: registry.insolar.io/explorer
    username: ((meta.registry.username))
    password: ((meta.registry.password))

- name: k8s
  type: kubernetes
  source:
    server: https://kube.insolar.io:6443
    token: ((meta.kubernetes.explorer.token))
    certificate_authority: ((meta.kubernetes.ca))

jobs:
- name: build-explorer
  plan:
    - get: git-explorer
      trigger: true
    - get: adm
      trigger: false
    - task: build-explorer
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: alpine/git}
        inputs:
        - name: git-explorer
        - name: adm
        outputs:
        - name: artifacts
        run:
          path: sh
          args:
            - -exc
            - |
               cp git-explorer/.git/short_ref artifacts/docker-tag
               cp git-explorer/nginx.conf artifacts/nginx.conf
               cp adm/manifests/explorer/explorer.yaml artifacts/explorer.yaml
               sed -i "s/registry.insolar.io\/explorer/registry.insolar.io\/explorer:$(cat artifacts/docker-tag)/g" artifacts/explorer.yaml

               echo create Dockerfile
               cat << EOF > git-explorer/.env.production
               REACT_APP_API_URL=https://explorer.insolar.io/api
               EOF
               cat << EOF > git-explorer/Dockerfile
               FROM node:8-alpine as builder
               ADD . /site
               WORKDIR /site
               RUN rm -Rf build/* && npm i && npm run build

               FROM nginx:alpine as site
               COPY --from=builder /site/build /usr/share/nginx/html
               COPY nginx.conf /usr/share/nginx/html/nginx.conf
               EOF
               cat git-explorer/Dockerfile
               rm -Rf git-explorer/site/*
               mv git-explorer/* artifacts/
               mv git-explorer/.env.production artifacts/
               ls -alh
    - put: registry-explorer
      get_params: {skip_download: true}
      params:
        build: artifacts
        target: site
        tag_file: artifacts/docker-tag
        tag_as_latest: true
    - put: k8s
      params:
        namespace: ((meta.kubernetes.explorer.namespace))
        kubectl: apply -f artifacts/explorer.yaml




