global:
  scrape_interval: 10s
  scrape_timeout: 2s

scrape_configs:

- job_name: virtual
  static_configs:
  - targets:
    - "host.docker.internal:8001"

- job_name: virtual_runner
  static_configs:
  - targets:
    - "host.docker.internal:8002"

